"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const shape_1 = require("./shape");
const Circle_1 = require("./Circle");
const Rectangle_1 = require("./Rectangle");
let myShape = new shape_1.Shape(10, 20);
console.log(myShape.getInfo());
let myCircle = new Circle_1.Circle(30, 40, 50);
console.log(myCircle.getInfo());
let myRectangle = new Rectangle_1.Rectangle(10, 20, 30, 40);
console.log(myRectangle.getInfo());
